# Generated by Django 6.0.5 on 2026-05-13 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUI', 'Quinta-feira'), ('SAB', 'Sábado')], max_length=3)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('vagas_totais', models.IntegerField(default=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('dia_semana', 'hora_inicio', 'hora_fim')},
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Pix'), ('PAGO', 'Confirmado'), ('CANCELADO', 'Cancelado/Expirado')], default='PENDENTE', max_length=10)),
                ('id_transacao_mp', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_horario', to='app_reservas.horario')),
            ],
            options={
                'ordering': ['-data_aula', 'horario__hora_inicio'],
            },
        ),
    ]
