# Generated by Django 6.0.5 on 2026-06-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservas', '0002_horario_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Pix'), ('PAGO', 'Confirmado'), ('CANCELADO', 'Cancelado/Expirado'), ('COMPARECEU', 'Compareceu'), ('FALTOU', 'Faltou')], default='PENDENTE', max_length=10),
        ),
    ]
