# Generated by Django 6.0.5 on 2026-06-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservas', '0005_alter_horario_dia_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='data_exata',
            field=models.DateField(blank=True, help_text='Preencha APENAS se for um evento de dia único. Deixe em branco para turmas que se repetem toda semana.', null=True),
        ),
    ]
