# Generated by Django 6.0.5 on 2026-06-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservas', '0006_horario_data_exata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='tipo_plano',
            field=models.CharField(choices=[('AVULSO', 'Avulso'), ('MENSAL', 'Mensalista'), ('BOLSISTA', 'Bolsista')], default='AVULSO', max_length=20),
        ),
    ]
